language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

# Travis CI 서버의Home
cache:
  directories:
    -  '$HOME/.m2/repository'
    -  '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
    - mkdir -p before-deploy
    - cd script/*.sh before-deploy/
    - cd appspec.yml before-deploy/
    - cd build/libs/*.jar before-deploy/
    - cd before-deploy && zip -r before-deploy *
    - cd ../ && mkdir -p deploy
    - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-webservice-build
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - zuiop13@naver.com